### ISSUE TITLE
備考欄を追加

### ISSUE THREAD

**Issue by niwaniwa** [niwaniwa/MisskeyEmojiBot#2]
# 概要
ライセンスなどの記載ができるように備考の設定を追加する

**Comment by niwaniwa** [comment]
resolve #49

**Comment by Sayamame-beans** [comment]
透過版に置き換えて欲しい場合などに、備考欄に記載して申請出来ると良いかも?という意見が出ていたので、備考とライセンスは別で用意した方が良いような気もします…?

https://misskey.niri.la/notes/9hctguzp39
> 申請する時に備考とか送れると嬉しいかも？

**Comment by niwaniwa** [comment]
現状だと絵文字情報を保持できない点と備考欄がmisskey にないということからやむを得ずライセンスに統合している側面があり、、、
どうしましょう

**Comment by Sayamame-beans** [comment]
備考情報はスレッドで閲覧出来れば十分と思っていました(承認するときにモデレーターが確認する用を想定していたので…)

**Comment by niwaniwa** [comment]
なるほど！
から別で設けても良いですね
別issue作成しますか
