### ISSUE TITLE
申請場所をチャンネルじゃなくてスレッドにする

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/MisskeyEmojiBot#43]
チャンネルはカテゴリ内の上限が50個であるため。
承認完了後はスレッド削除で良さそう。(残す理由があまり無さそうなので)

**Comment by niwaniwa** [comment]
Discordの仕様とEmojiBotの仕様の兼ね合いでしばらく見送り

**Comment by niwaniwa** [comment]
補足すると、どうやら一つのメッセージに付与できるスレッドが一つのみなので、二つ以上つけるとエラーが出てしまいます。(メッセージを増やせばいいですが、他の人から見れたりできるのでどうしようかなと

**Comment by Sayamame-beans** [comment]
private threadではメッセージを指定しなくて良い気がします…?(少なくとも、discord.pyでは[そのよう](https://discordpy.readthedocs.io/ja/latest/api.html#discord.TextChannel.create_thread)に見えるので、discordgoではどうなのか調べてみます)

**Comment by niwaniwa** [comment]
:nandatte: 私も確認してみます

**Comment by Sayamame-beans** [comment]
https://pkg.go.dev/github.com/bwmarrin/discordgo#Session.MessageThreadStartComplex は既存のメッセージをベースにパブリックなスレッドを作成するのに使うメソッドのように見えますね。
実際に使ってみないと分かりませんが、 https://pkg.go.dev/github.com/bwmarrin/discordgo#Session.ThreadStartComplex を使って、その引数の[ThreadStart](https://pkg.go.dev/github.com/bwmarrin/discordgo#ThreadStart)の[ChannelType](https://pkg.go.dev/github.com/bwmarrin/discordgo#ChannelType)でprivate threadを指定すれば出来たりするかも…?
ついでにInvitableはfalseの方が良さそう。

**Comment by niwaniwa** [comment]
上手くできた！
