### ISSUE TITLE
低速モードの必要性?

### ISSUE THREAD

**Issue by Sayamame-beans** [niwaniwa/MisskeyEmojiBot#68]
現在は10秒に1回のみ投稿可能となっている。
https://github.com/niwaniwa/MisskeyEmojiBot/blob/3ee3b0ed5cf83680cffc5fadb49017820ef0af87/component.go#L283
https://github.com/niwaniwa/MisskeyEmojiBot/blob/3ee3b0ed5cf83680cffc5fadb49017820ef0af87/component.go#L402

**Comment by Sayamame-beans** [comment]
もう少し短くするか、失くしてしまっても良さそう。

**Comment by Sayamame-beans** [comment]
初期値0な気がするので、失くす場合はこのパラメーターを指定しないだけで解決するかもです

**Comment by niwaniwa** [comment]
#69
